# Generated by Django 4.0.6 on 2022-08-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('file_one', models.FileField(upload_to='media/file_one')),
                ('file_two', models.FileField(upload_to='media/file_two')),
                ('output_file', models.FileField(upload_to='media/output_file')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
