# Generated by Django 4.0.6 on 2022-08-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theModels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='output_file',
        ),
    ]
