# Generated by Django 4.0.6 on 2022-08-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file_upload', models.FileField(upload_to='media')),
                ('sid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.student')),
            ],
        ),
    ]
